apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kagent

  source:
    repoURL: oci://ghcr.io/kagent-dev/kagent/helm
    chart: kagent
    targetRevision: 0.9.6

    helm:
      values: |
        providers:
          openAI:
            apiKey: "dummy-key"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
