apiVersion: apps/v1
kind: Deployment

metadata:
  name: langgraph
  namespace: ai-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: langgraph

  template:
    metadata:
      labels:
        app: langgraph

    spec:
      containers:
      - name: langgraph

        image: ghcr.io/inoovaid/langgraph:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8000

        env:
        - name: OLLAMA_HOST
          value: "http://ollama-agents.ai-system.svc.cluster.local:11434"

        - name: DATABASE_URI
          value: "postgresql://appuser:AppPass123@postgres-ha-rw.default.svc.cluster.local:5432/langgraph"

        - name: REDIS_URI
          value: "redis://redis-langgraph.ai-system.svc.cluster.local:6379"
