apiVersion: apps/v1
kind: Deployment

metadata:
  name: langgraph
  namespace: ai-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: langgraph

  template:
    metadata:
      labels:
        app: langgraph

    spec:

      containers:

      - name: langgraph

        image: heiffigjr/langgraph:latest

        imagePullPolicy: Always

        env:

        - name: OLLAMA_HOST
          value: "http://ollama-agents.ai-system.svc.cluster.local:11434"

        resources:
          requests:
            cpu: 100m
            memory: 256Mi

          limits:
            cpu: "1"
            memory: 1Gi
