apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: langgraph
  namespace: ai-system

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  ingressClassName: nginx

  tls:
  - hosts:
    - langgraph.dnn.lat
    secretName: wildcard-dnn

  rules:
  - host: langgraph.dnn.lat

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: langgraph
            port:
              number: 80
