apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: nginx
        image: heiffigjr/frontend-app:51c33f6e2877debe3d94931313a07f2522dd1a6d
        ports:
        - containerPort: 80
