apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: nginx
        image: heiffigjr/frontend-app:65bcc978c91b262ebf9d912f0b1c6de0a78af484
        ports:
        - containerPort: 80
