apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: nginx
        image: heiffigjr/frontend-app:32c5e337345cfd3ee2a54358f66fac2543ac7197
        ports:
        - containerPort: 80
