apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
data:
  username: <base64-encoded-username>  # Base64 do nome de usuário
  password: <base64-encoded-password>  # Base64 da senha
