apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: keycloak

  template:
    metadata:
      labels:
        app: keycloak

    spec:
      terminationGracePeriodSeconds: 30

      # 🔥 GARANTE QUE O BANCO ESTÁ PRONTO
      initContainers:
        - name: wait-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z postgres-ha-rw.default.svc.cluster.local 5432; do
                echo "⏳ waiting for postgres..."
                sleep 5
              done

      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.3

          args: ["start"]

          ports:
            - containerPort: 8080

          env:
            # 🔥 DATABASE
            - name: KC_DB
              value: postgres

            - name: KC_DB_URL_HOST
              value: postgres-ha-rw.default.svc.cluster.local

            - name: KC_DB_URL_PORT
              value: "5432"

            - name: KC_DB_URL_DATABASE
              value: keycloak

            - name: KC_DB_USERNAME
              value: keycloak

            - name: KC_DB_PASSWORD
              value: keycloak

            # 🔥 PRODUÇÃO (OBRIGATÓRIO)
            - name: KC_HOSTNAME
              value: login-cloud.dnn.lat

            - name: KC_HOSTNAME_STRICT
              value: "false"

            - name: KC_PROXY
              value: edge

            # 🔐 ADMIN
            - name: KEYCLOAK_ADMIN
              value: admin

            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"

          # 🔥 STARTUP (evita CrashLoop)
          startupProbe:
            httpGet:
              path: /health/ready
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
