apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: keycloak

  template:
    metadata:
      labels:
        app: keycloak

    spec:
      terminationGracePeriodSeconds: 30

      initContainers:
        - name: wait-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z postgres-ha-rw.default.svc.cluster.local 5432; do
                echo "waiting for postgres..."
                sleep 5
              done

      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.3

          args: ["start-dev"]

          ports:
            - containerPort: 8080

          env:
            - name: KC_DB
              value: postgres

            - name: KC_DB_URL_HOST
              value: postgres-ha-rw.default.svc.cluster.local

            - name: KC_DB_URL_PORT
              value: "5432"

            - name: KC_DB_URL_DATABASE
              value: keycloak

            - name: KC_DB_USERNAME
              value: appuser

            - name: KC_DB_PASSWORD
              value: AppPass123

            - name: KC_HOSTNAME
              value: login-cloud.dnn.lat

            - name: KC_HOSTNAME_STRICT
              value: "false"

            - name: KC_PROXY
              value: edge

            - name: KEYCLOAK_ADMIN
              value: admin

            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak

spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - port: 80
      targetPort: 8080
