apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-web-iis
  namespace: saas-web-iis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-web-iis
  template:
    metadata:
      labels:
        app: saas-web-iis
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
