apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd

spec:
  project: default

  destination:
    namespace: observability
    server: https://kubernetes.default.svc

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.47.2

    helm:
      values: |
        loki:
          auth_enabled: false

          limits_config:
            ingestion_rate_mb: 10
            ingestion_burst_size_mb: 20
    
          commonConfig:
            replication_factor: 2

          storage:
            type: s3

          storage_config:
            aws:
              s3: http://minio.observability.svc.cluster.local:9000
              bucketnames: loki
              access_key_id: admin
              secret_access_key: admin123
              s3forcepathstyle: true

          schemaConfig:
            configs:
              - from: 2024-01-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

          ring:
            kvstore:
              store: memberlist

          memberlist:
            join_members:
              - loki-headless

        singleBinary:
          replicas: 2

        service:
          type: ClusterIP

        monitoring:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
