apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperclip

resources:
  - namespace.yaml
  - leader-election-role.yaml   # Role + RoleBinding (juntos no mesmo arquivo)
  - sealed-secrets.yaml
  - instance.yaml
  - ingress.yaml
