grafana:
  enabled: true
  adminPassword: admin

  persistence:
    enabled: true
    size: 5Gi

prometheus:
  prometheusSpec:
    retention: 7d

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: false
