{
 "title": "Loki Logs (Inoova)",
 "panels": [
  {
   "title": "Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"observability\"}"
    }
   ]
  },
  {
   "title": "Total Logs (últimos 5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"observability\"}[5m])"
    }
   ]
  },
  {
   "title": "Taxa de Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate({namespace=\"observability\"}[1m])"
    }
   ]
  }
 ]
}