grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - grafana-cloud.dnn.lat

    tls:
      - secretName: wildcard-dnn
        hosts:
          - grafana-cloud.dnn.lat

prometheus:
  service:
    type: ClusterIP

alertmanager:
  enabled: true
