apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    namespace: observability
    server: https://kubernetes.default.svc

  sources:
    - repoURL: https://github.com/inoovaid/inoova-cloud-apps
      targetRevision: main
      ref: values

    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 58.3.1
      helm:
        valueFiles:
          - $values/observability/prometheus/prometheus-values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
