apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.0.0

    helm:
      values: |
        grafana:
          enabled: true
          adminPassword: admin

          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.observability.svc.cluster.local:3100
              access: proxy

          persistence:
            enabled: false

          service:
            type: ClusterIP
            port: 80

          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana-cloud.dnn.lat
            path: /
            pathType: Prefix
            tls:
              - hosts:
                  - grafana-cloud.dnn.lat
                secretName: wildcard-dnn

          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              folder: /tmp/dashboards
            
            datasources:
              enabled: true
              defaultDatasourceEnabled: true

            dashboardProviders:
              dashboardproviders.yaml:
                apiVersion: 1
                providers:
                  - name: 'default'
                    orgId: 1
                    folder: ''
                    type: file
                    disableDeletion: false
                    editable: true
                    options:
                      path: /tmp/dashboards

        prometheus:
          enabled: true

        alertmanager:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
