apiVersion: v1
kind: ConfigMap

metadata:
  name: openclaw-config
  namespace: openclaw

data:
  openclaw.json: |
    {
      "gateway": {
        "mode": "local"
      }
    }

  AGENTS.md: |
    # OpenClaw Agents
