apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: argocd
  labels:
    project: default
spec:
  project: default
  source:
    repoURL: https://github.com/inoovaid/inoova-cloud-apps.git
    targetRevision: HEAD
    path: AIOps/agents/openclaw
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
