apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd

spec:
  project: default

  destination:
    namespace: observability
    server: https://kubernetes.default.svc

  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.0.15

    helm:
      values: |
        mode: standalone

        rootUser: admin
        rootPassword: admin

        persistence:
          enabled: true
          size: 5Gi

        command:
          - /bin/sh
          - -c
        args:
          - minio server /data --console-address ":9001"

        service:
          type: ClusterIP

        resources:
          requests:
            memory: 256Mi
            cpu: 100m

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
