resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - ollama/ollama.yaml
  - ollama-agents/ollama-agents.yaml
#  - mcp-servers/kubernetes/base
  - mcp-servers/mcp-hub/overlays/prod
