apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-hub
  namespace: ai-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-hub
  template:
    metadata:
      labels:
        app: mcp-hub
    spec:
      containers:
      - name: supergateway
        image: supercorp/supergateway:3.4.3
        imagePullPolicy: Always
        args:
          - --streamableHttp
          - http://mcp-kubernetes:8000/mcp
        ports:
        - containerPort: 8000
