apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-dashboards
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/inoovaid/inoova-cloud-apps
    targetRevision: main
    path: observability/grafana

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
