#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://github.com/inoovaid/inoova-cloud-apps
    targetRevision: main
    path: observability/grafana
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.52.2
    helm:
      valueFiles:
        - $values/observability/grafana/grafana-values.yaml
  - repoURL: https://github.com/inoovaid/inoova-cloud-apps
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
