apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: inoova-apps
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/inoovaid/inoova-cloud-apps
        revision: HEAD
        directories:
          - path: k8s/*              # 👈 mantém tudo que já existe
          - path: k8s/saas-web-*     # 👈 novos apps automáticos
          - path: saas/web/*

  template:
    metadata:
      name: 'saas-{{path.dirname | basename}}'

    spec:
      project: default

      source:
        repoURL: https://github.com/inoovaid/inoova-cloud-apps
        targetRevision: HEAD
        path: '{{path}}'
  
      destination:
        server: https://kubernetes.default.svc
        namespace: 'saas-{{path.dirname | basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
