apiVersion: v1
kind: Namespace
metadata:
  name: ai-automation

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: ai-automation

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: ai-automation

spec:
  replicas: 1

  selector:
    matchLabels:
      app: n8n

  template:
    metadata:
      labels:
        app: n8n

    spec:
      containers:

      - name: n8n

        image: n8nio/n8n:latest

        ports:
        - containerPort: 5678

        env:

        - name: DB_TYPE
          value: postgresdb

        - name: DB_POSTGRESDB_HOST
          value: postgres-ha-rw.default.svc.cluster.local

        - name: DB_POSTGRESDB_PORT
          value: "5432"

        - name: DB_POSTGRESDB_DATABASE
          value: n8n

        - name: DB_POSTGRESDB_USER
          value: appuser

        - name: DB_POSTGRESDB_PASSWORD
          value: AppPass123

        - name: N8N_HOST
          value: n8n-agent.dnn.lat

        - name: WEBHOOK_URL
          value: https://n8n-agent.dnn.lat

        - name: N8N_PROTOCOL
          value: https

        - name: N8N_PORT
          value: "5678"

        - name: GENERIC_TIMEZONE
          value: America/Sao_Paulo

        - name: TZ
          value: America/Sao_Paulo

        - name: N8N_SECURE_COOKIE
          value: "false"

        volumeMounts:
        - mountPath: /home/node/.n8n
          name: n8n-data

      volumes:
      - name: n8n-data

        persistentVolumeClaim:
          claimName: n8n-data

---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: ai-automation

spec:
  selector:
    app: n8n

  ports:
  - port: 80
    targetPort: 5678
