grafana:
  enabled: true
  adminPassword: admin

  persistence:
    enabled: false

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana-cloud.dnn.lat
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - grafana-cloud.dnn.lat
        secretName: wildcard-dnn

  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: false   # 🔥 ISSO AQUI RESOLVE
