helm:
  skipCrds: true
  values: |
    grafana:
      enabled: true

      adminPassword: admin

      service:
        type: ClusterIP
        port: 80

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

        hosts:
          - grafana-cloud.dnn.lat

        path: /
        pathType: Prefix

        tls:
          - hosts:
              - grafana-cloud.dnn.lat
            secretName: wildcard-dnn

      # 🔥 AQUI É A ÚNICA COISA QUE VOCÊ PRECISA
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-stack.observability:3100

    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false

    alertmanager:
      enabled: true

    nodeExporter:
      enabled: true

    kubeStateMetrics:
      enabled: true
