# ===============================
# PROMETHEUS STACK CONFIG
# ===============================

grafana:
  enabled: true

  adminPassword: admin

  service:
    type: ClusterIP

  ingress:
    enabled: false   # você já usa ingress separado (CORRETO)

  persistence:
    enabled: false   # pode ativar depois se quiser

  # 🔥 DATASOURCES (O MAIS IMPORTANTE)
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-stack-kube-prom-prometheus.observability:9090
      isDefault: true

    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.observability:3100

# ===============================
# PROMETHEUS
# ===============================

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

# ===============================
# ALERTMANAGER
# ===============================

alertmanager:
  enabled: true

# ===============================
# NODE EXPORTER
# ===============================

nodeExporter:
  enabled: true

# ===============================
# KUBE STATE METRICS
# ===============================

kubeStateMetrics:
  enabled: true
