grafana:
  enabled: true

  adminPassword: admin

  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.observability:3100

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
