grafana:
  enabled: true

  adminPassword: admin

  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - grafana-cloud.dnn.lat

    path: /
    pathType: Prefix

    tls:
      - hosts:
          - grafana-cloud.dnn.lat
        secretName: wildcard-dnn

  # 🔥 ESSENCIAL
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.observability:3100
      isDefault: false   # 🔥 ISSO RESOLVE O ERRO

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
