loki:
  auth_enabled: false

singleBinary:
  replicas: 1

persistence:
  enabled: false

monitoring:
  enabled: false

gateway:
  enabled: false

# 🔥 DESATIVA COMPLETAMENTE O AGENT
grafanaAgent:
  enabled: false

# 🔥 REMOVE QUALQUER COISA RELACIONADA
agent:
  enabled: false
