loki:
  enabled: true

promtail:
  enabled: true

grafana:
  enabled: false

prometheus:
  enabled: false

# 💣 DESATIVA QUALQUER DATASOURCE AUTOMÁTICO
loki-stack:
  grafana:
    enabled: false

# 🔥 FORÇA NÃO CRIAR DATASOURCE
extraObjects: []
