# infra/argocd/ingress.yaml
apiVersion: argoproj.io/v1alpha1
kind: Ingress
metadata:
  name: root-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/inoovaid/inoova-cloud-apps.git
    targetRevision: main
    path: infra

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
