name: Build e Push Docker (Multi SaaS)

on:
  push:
    paths:
      - 'saas/web/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app:
          - app
          - financeflow   # 🔥 adiciona aqui
          # - crm2 (futuro)
          # - crm3 (futuro)

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build imagem
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/saas-web-${{ matrix.app }}:latest ./saas/web/${{ matrix.app }}

      - name: Push imagem
        run: |
          docker push ${{ secrets.DOCKER_USER }}/saas-web-${{ matrix.app }}:latest
