name: Build e Push Docker (Auto SaaS)

on:
  push:
    paths:
      - 'saas/web/**'
    branches:
      - main

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.set.outputs.apps }}

    steps:
      - uses: actions/checkout@v3

      - id: set
        run: |
          apps=$(ls saas/web | jq -R -s -c 'split("\n")[:-1]')
          echo "apps=$apps" >> $GITHUB_OUTPUT

  build:
    needs: detect
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ${{ fromJson(needs.detect.outputs.apps) }}

    steps:
      - uses: actions/checkout@v3

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build imagem
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/saas-${{ matrix.app }}:latest ./saas/web/${{ matrix.app }}

      - name: Push imagem
        run: |
          docker push ${{ secrets.DOCKER_USER }}/saas-${{ matrix.app }}:latest
