name: Build LangGraph

on:
  push:
    paths:
      - 'AIOps/langgraph-app/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USER }}/langgraph:latest \
            ./AIOps/langgraph-app

      - name: Push
        run: |
          docker push \
            ${{ secrets.DOCKER_USER }}/langgraph:latest
